# POST http://localhost:3333/orphanages HTTP/1.1
# content-type: application/json

# {
#   "name": "Lar das meninas",
#   "latitude": -13.2282185,
#   "longitude": -39.5128642,
#   "about": "Sobre o orfanatos",
#   "instructions": "Venha visitar",
#   "opening_hours": "Das 8 as 15",
#   "open_on_weekends": true
# }


POST http://localhost:3333/orphanages
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="/home/han/Workspace/gitWorkspace/NLW/happy/backend/restRequisitions/liiindoooo.png"
Content-Type: image/png

< ./liiindoooo.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

{
  "name": "Lar das meninas",
  "latitude": -13.2282185,
  "longitude": -39.5128642,
  "about": "Sobre o orfanatos",
  "instructions": "Venha visitar",
  "opening_hours": "Das 8 as 15",
  "open_on_weekends": true
}
